/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrisedental.gui;

import com.sunrisedental.client.DentistApiClient;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sunrisedental.model.Dentist;
import com.sunrisedental.model.User;

import java.net.http.HttpResponse;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iffah
 */
public class DentistForm extends javax.swing.JFrame {
    private User currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DentistForm.class.getName());

    /**
     * Creates new form DentistForm
     */
    public DentistForm() {
        initComponents();
    }
    
    public DentistForm(User currentUser) {

    initComponents();

    this.currentUser = currentUser;

    
        setLocationRelativeTo(null);

        txtDentistId.setEditable(false);

        loadDentists();
}
    
    private final DentistApiClient dentistApiClient =
        new DentistApiClient();

private final ObjectMapper objectMapper =
        new ObjectMapper()
                .findAndRegisterModules()
                .configure(
                        com.fasterxml.jackson.databind.DeserializationFeature
                                .FAIL_ON_UNKNOWN_PROPERTIES,
                        false
                );
    private void loadDentists() {

    try {

        HttpResponse<String> response =
                dentistApiClient.getAllDentists();

        if (response.statusCode() != 200) {

            showApiError(
                    response,
                    "Load Dentists Error"
            );

            return;
        }

        List<Dentist> dentists =
                objectMapper.readValue(
                        response.body(),
                        new TypeReference<List<Dentist>>() {}
                );

        DefaultTableModel model =
                (DefaultTableModel)
                tblDentists.getModel();

        model.setRowCount(0);

        for (Dentist dentist : dentists) {

            model.addRow(new Object[]{

                dentist.getDentistId(),
                dentist.getDentistName(),
                dentist.getContactNumber(),
                dentist.getSpecialization(),
                dentist.isActive()

            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Load Dentists Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDentistId = new javax.swing.JTextField();
        txtDentistName = new javax.swing.JTextField();
        txtDentistContact = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        chkActive = new javax.swing.JCheckBox();
        btnSaveDentist = new javax.swing.JButton();
        btnUpdateDentist = new javax.swing.JButton();
        btnClearDentist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDentists = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DENTIST MANAGEMENT");

        jLabel2.setText("Dentist ID:");

        jLabel3.setText("Dentist Name: ");

        jLabel4.setText("Contact Number:");

        jLabel5.setText("Specialization:");

        jLabel6.setText("Active: ");

        btnSaveDentist.setText("SAVE");
        btnSaveDentist.addActionListener(this::btnSaveDentistActionPerformed);

        btnUpdateDentist.setText("UPDATE");
        btnUpdateDentist.addActionListener(this::btnUpdateDentistActionPerformed);

        btnClearDentist.setText("CLEAR");

        tblDentists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dentist  Id", "Dentist Name", "Contact", "Specialization", "Active"
            }
        ));
        tblDentists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDentistsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDentists);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveDentist)
                                .addGap(48, 48, 48)
                                .addComponent(btnUpdateDentist)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearDentist))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDentistId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDentistName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDentistContact, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkActive, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDentistId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDentistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDentistContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkActive))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveDentist)
                    .addComponent(btnUpdateDentist)
                    .addComponent(btnClearDentist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveDentistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDentistActionPerformed
        // TODO add your handling code here:
        try {

        Dentist dentist = new Dentist();

        dentist.setDentistName(
                txtDentistName.getText().trim()
        );

        dentist.setContactNumber(
                txtDentistContact.getText().trim()
        );

        dentist.setSpecialization(
                txtSpecialization.getText().trim()
        );

        dentist.setActive(
                chkActive.isSelected()
        );

        String json =
                objectMapper.writeValueAsString(
                        dentist
                );

        System.out.println(
                "CREATE DENTIST JSON:"
        );

        System.out.println(json);

        HttpResponse<String> response =
                dentistApiClient.createDentist(
                        json
                );

        if (response.statusCode() == 201) {

            Dentist createdDentist =
                    objectMapper.readValue(
                            response.body(),
                            Dentist.class
                    );

            txtDentistId.setText(
                    String.valueOf(
                            createdDentist.getDentistId()
                    )
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist saved successfully.\n"
                    + "Dentist ID: "
                    + createdDentist.getDentistId()
            );

            loadDentists();

        } else {

            showApiError(
                    response,
                    "Save Dentist Error"
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Save Dentist Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSaveDentistActionPerformed

    private void tblDentistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDentistsMouseClicked
        // TODO add your handling code here:
        try {

        int row =
                tblDentists.getSelectedRow();

        if (row == -1) {
            return;
        }

        int dentistId =
                Integer.parseInt(
                        tblDentists
                                .getValueAt(row, 0)
                                .toString()
                );

        HttpResponse<String> response =
                dentistApiClient.getDentist(
                        dentistId
                );

        if (response.statusCode() != 200) {

            showApiError(
                    response,
                    "Dentist Error"
            );

            return;
        }

        Dentist dentist =
                objectMapper.readValue(
                        response.body(),
                        Dentist.class
                );

        txtDentistId.setText(
                String.valueOf(
                        dentist.getDentistId()
                )
        );

        txtDentistName.setText(
                dentist.getDentistName()
        );

        txtDentistContact.setText(
                dentist.getContactNumber()
        );

        txtSpecialization.setText(
                dentist.getSpecialization()
        );

        chkActive.setSelected(
                dentist.isActive()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Dentist Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_tblDentistsMouseClicked

    private void btnUpdateDentistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDentistActionPerformed
        // TODO add your handling code here:
        try {

        if (txtDentistId.getText()
                .trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please select a dentist first."
            );

            return;
        }

        int dentistId =
                Integer.parseInt(
                        txtDentistId.getText().trim()
                );

        Dentist dentist = new Dentist();

        dentist.setDentistId(dentistId);

        dentist.setDentistName(
                txtDentistName.getText().trim()
        );

        dentist.setContactNumber(
                txtDentistContact.getText().trim()
        );

        dentist.setSpecialization(
                txtSpecialization.getText().trim()
        );

        dentist.setActive(
                chkActive.isSelected()
        );

        String json =
                objectMapper.writeValueAsString(
                        dentist
                );

        System.out.println(
                "UPDATE DENTIST JSON:"
        );

        System.out.println(json);

        HttpResponse<String> response =
                dentistApiClient.updateDentist(
                        dentistId,
                        json
                );

        if (response.statusCode() == 200) {

            JOptionPane.showMessageDialog(
                    this,
                    "Dentist updated successfully."
            );

            loadDentists();

        } else {

            showApiError(
                    response,
                    "Update Dentist Error"
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid dentist ID.",
                "Update Dentist Error",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Update Dentist Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnUpdateDentistActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         goBackToDashboard();
    }//GEN-LAST:event_btnBackActionPerformed

    private void showApiError(
        HttpResponse<String> response,
        String title) {

    String message =
            "HTTP Status: "
            + response.statusCode()
            + "\n\n"
            + "Server Response:\n"
            + response.body();

    JOptionPane.showMessageDialog(
            this,
            message,
            title,
            JOptionPane.ERROR_MESSAGE
    );
}
    
    private void goBackToDashboard() {

    DashboardForm dashboard =
            new DashboardForm(currentUser);

    dashboard.setVisible(true);

    this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DentistForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearDentist;
    private javax.swing.JButton btnSaveDentist;
    private javax.swing.JButton btnUpdateDentist;
    private javax.swing.JCheckBox chkActive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDentists;
    private javax.swing.JTextField txtDentistContact;
    private javax.swing.JTextField txtDentistId;
    private javax.swing.JTextField txtDentistName;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
