package com.sunrisedental.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.sunrisedental.client.ReportApiClient;
import com.sunrisedental.report.AppointmentDetails;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sunrisedental.model.User;

import java.net.http.HttpResponse;
import java.time.LocalDate;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iffah
 */
public class ReportsForm extends javax.swing.JFrame {
    private User currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportsForm.class.getName());

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
    }
    public ReportsForm(User currentUser) {

    initComponents();

    this.currentUser = currentUser;
}
    
    private final ReportApiClient reportApiClient =
        new ReportApiClient();

private final ObjectMapper objectMapper =
        new ObjectMapper()
                .findAndRegisterModules()
                .configure(
                        com.fasterxml.jackson.databind.DeserializationFeature
                                .FAIL_ON_UNKNOWN_PROPERTIES,
                        false
                );

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerateDailyReport = new javax.swing.JButton();
        txtReportDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        btnClearReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REPORTS                            ");

        jLabel2.setText("Report Date:");

        btnGenerateDailyReport.setText("GENERATE DAILY APPOINTMENT REPORT");
        btnGenerateDailyReport.addActionListener(this::btnGenerateDailyReportActionPerformed);

        txtReportDate.setText("YYYY-MM-DD");
        txtReportDate.addActionListener(this::txtReportDateActionPerformed);

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment No ", "Patient Name ", "Dentist", "Treatment ", "Date ", "Time ", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        btnClearReport.setText("CLEAR");
        btnClearReport.addActionListener(this::btnClearReportActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerateDailyReport)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnClearReport))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtReportDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerateDailyReport)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearReport)
                        .addGap(232, 232, 232))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateDailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateDailyReportActionPerformed
        // TODO add your handling code here:
        try {

        String dateText =
                txtReportDate
                        .getText()
                        .trim();

        if (dateText.isEmpty() ||
                dateText.equalsIgnoreCase("YYYY-MM-DD")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter a report date.",
                    "Report Error",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Validate date locally first.

        LocalDate reportDate =
                LocalDate.parse(dateText);


        // ==========================================
        // CALL REST API
        // ==========================================

        HttpResponse<String> response =
                reportApiClient
                        .getDailyAppointments(
                                reportDate.toString()
                        );


        // ==========================================
        // CHECK RESPONSE
        // ==========================================

        if (response.statusCode() != 200) {

            showApiError(
                    response,
                    "Report Error"
            );

            return;
        }


        // ==========================================
        // CONVERT JSON TO OBJECTS
        // ==========================================

        List<AppointmentDetails> appointments =
                objectMapper.readValue(
                        response.body(),
                        new TypeReference<
                                List<AppointmentDetails>
                        >() {}
                );


        // ==========================================
        // UPDATE TABLE
        // ==========================================

        DefaultTableModel model =
                (DefaultTableModel)
                tblReport.getModel();

        model.setRowCount(0);


        for (AppointmentDetails appointment
                : appointments) {

            model.addRow(new Object[]{

                appointment.appointmentNo,
                appointment.patientName,
                appointment.dentistName,
                appointment.treatmentName,
                appointment.appointmentDate,
                appointment.appointmentTime,
                appointment.status

            });
        }


        // ==========================================
        // NO RESULTS
        // ==========================================

        if (appointments.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "No appointments found for "
                    + reportDate,
                    "Daily Report",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }

    } catch (
            java.time.format.DateTimeParseException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter date as YYYY-MM-DD.",
                "Report Error",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Report Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnGenerateDailyReportActionPerformed

    private void txtReportDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportDateActionPerformed

    private void btnClearReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearReportActionPerformed
        // TODO add your handling code here:
        txtReportDate.setText("");

    DefaultTableModel model =
            (DefaultTableModel)
            tblReport.getModel();

    model.setRowCount(0);
    }//GEN-LAST:event_btnClearReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         goBackToDashboard();
    }//GEN-LAST:event_btnBackActionPerformed

    private void showApiError(
        HttpResponse<String> response,
        String title) {

    JOptionPane.showMessageDialog(
            this,
            "HTTP Status: "
            + response.statusCode()
            + "\n\nServer Response:\n"
            + response.body(),
            title,
            JOptionPane.ERROR_MESSAGE
    );
}
    
    private void goBackToDashboard() {

    DashboardForm dashboard =
            new DashboardForm(currentUser);

    dashboard.setVisible(true);

    this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearReport;
    private javax.swing.JButton btnGenerateDailyReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtReportDate;
    // End of variables declaration//GEN-END:variables
}
