/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sunrisedental.gui;

import com.sunrisedental.dao.UserDAO;
import com.sunrisedental.model.User;
import com.sunrisedental.service.AuthService;
import com.sunrisedental.service.UserService;
import com.sunrisedental.util.PasswordUtil;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iffah
 */
public class UserForm extends javax.swing.JFrame {
    private User currentUser;
    private UserDAO userDAO = new UserDAO();

    private UserService userService =
        new UserService();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserForm.class.getName());

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
    }
    
    public UserForm(User currentUser) {

    initComponents();

    this.currentUser = currentUser;

    setLocationRelativeTo(null);

    txtUserId.setEditable(false);

    cmbRole.removeAllItems();
    cmbRole.addItem("ADMIN");
    cmbRole.addItem("RECEPTIONIST");

    loadUsers();
}
   
    private void loadUsers() {

    try {

        List<User> users =
                userService.findAll();

        DefaultTableModel model =
                (DefaultTableModel)
                tblUsers.getModel();

        model.setRowCount(0);

        for (User user : users) {

            model.addRow(
                    new Object[]{

                        user.getUserId(),
                        user.getUsername(),
                        user.getFullName(),
                        user.getRole()

                    }
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error loading users: "
                + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSaveUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnClearUser = new javax.swing.JButton();
        txtSearchUsername = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtFullName = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        txtUserId = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USER MANAGEMENT");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("Confirm Password:");

        jLabel5.setText("Full Name:");

        jLabel6.setText("Role:  ");

        jLabel7.setText("Search:");

        btnSaveUser.setText("SAVE");
        btnSaveUser.addActionListener(this::btnSaveUserActionPerformed);

        btnUpdateUser.setText("UPDATE");
        btnUpdateUser.addActionListener(this::btnUpdateUserActionPerformed);

        btnDeleteUser.setText("DELETE");
        btnDeleteUser.addActionListener(this::btnDeleteUserActionPerformed);

        btnClearUser.setText("CLEAR");
        btnClearUser.addActionListener(this::btnClearUserActionPerformed);

        txtSearchUsername.addActionListener(this::txtSearchUsernameActionPerformed);

        btnSearchUser.setText("SEARCH");
        btnSearchUser.addActionListener(this::btnSearchUserActionPerformed);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "RECEPTIONIST" }));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Id", "Username", "Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        txtUserId.setEditable(false);

        lblMessage.setText("User Id");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSaveUser)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateUser)
                                .addGap(154, 154, 154)
                                .addComponent(btnDeleteUser))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearUser)
                            .addComponent(btnSearchUser)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveUser)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnClearUser))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtSearchUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnSearchUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserActionPerformed
        // TODO add your handling code here:
        try {

        String username =
                txtUsername.getText().trim();

        String fullName =
                txtFullName.getText().trim();

        String password =
                new String(
                        txtPassword.getPassword()
                );

        String confirmPassword =
                new String(
                        txtConfirmPassword.getPassword()
                );

        String role =
                cmbRole.getSelectedItem()
                        .toString();

        // Validate username
        if (username.isEmpty()) {

            throw new IllegalArgumentException(
                    "Please enter a username."
            );
        }

        // Validate full name
        if (fullName.isEmpty()) {

            throw new IllegalArgumentException(
                    "Please enter the full name."
            );
        }

        // Validate password
        if (password.isEmpty()) {

            throw new IllegalArgumentException(
                    "Please enter a password."
            );
        }

        // Confirm password
        if (!password.equals(confirmPassword)) {

            throw new IllegalArgumentException(
                    "Passwords do not match."
            );
        }

        // Check whether username already exists
        User existingUser =
                userService.findByUsername(username);

        if (existingUser != null) {

            throw new IllegalArgumentException(
                    "Username already exists."
            );
        }

        // Create User
        User user = new User();

        user.setUsername(username);

        user.setFullName(fullName);

        user.setRole(role);
        
        // Hash the password before saving
        user.setPassword(
                PasswordUtil.hashPassword(password)
        );

        // Save user
        userService.create(user);

        // Refresh table
        loadUsers();

        // Clear form
        clearUserForm();

        JOptionPane.showMessageDialog(
                this,
                "User created successfully."
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "User Registration Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSaveUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        try {

        // Check whether a user has been selected
        String userIdText =
                txtUserId.getText().trim();

        if (userIdText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please search and select a user first.",
                    "Delete User",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int userId =
                Integer.parseInt(userIdText);

        // Prevent the currently logged-in user
        // from deleting their own account
        if (currentUser != null
                && userId == currentUser.getUserId()) {

            JOptionPane.showMessageDialog(
                    this,
                    "You cannot delete your own "
                    + "currently logged-in account.",
                    "Delete User",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Ask for confirmation
        int choice =
                JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to delete "
                        + "this user?",
                        "Confirm Delete",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

        if (choice != JOptionPane.YES_OPTION) {
            return;
        }

        // Delete user from database
        userService.delete(userId);

        // Refresh table
        loadUsers();

        // Clear the form
        clearUserForm();

        JOptionPane.showMessageDialog(
                this,
                "User deleted successfully.",
                "Delete User",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Invalid user ID.",
                "Delete Error",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error deleting user: "
                + e.getMessage(),
                "Delete Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnClearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUserActionPerformed
        // TODO add your handling code here:
            clearUserForm();

    }//GEN-LAST:event_btnClearUserActionPerformed

    private void txtSearchUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUsernameActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        // TODO add your handling code here:
        try {

        String username =
                txtSearchUsername
                .getText()
                .trim();

        if (username.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter a username to search."
            );

            return;
        }

        User user =
                userService.findByUsername(
                        username
                );

        if (user == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "User not found."
            );

            return;
        }

        txtUserId.setText(
                String.valueOf(
                        user.getUserId()
                )
        );

        txtUsername.setText(
                user.getUsername()
        );

        txtFullName.setText(
                user.getFullName()
        );

        cmbRole.setSelectedItem(
                user.getRole()
        );

        // Never display the stored password
        txtPassword.setText("");

        txtConfirmPassword.setText("");

        selectUserRow(
                user.getUserId()
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Search Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        // TODO add your handling code here:
        try {

        String userIdText =
                txtUserId.getText().trim();

        if (userIdText.isEmpty()) {

            throw new IllegalArgumentException(
                    "Please search and select a user first."
            );
        }

        int userId =
                Integer.parseInt(userIdText);

        String username =
                txtUsername.getText().trim();

        String fullName =
                txtFullName.getText().trim();

        String password =
                new String(
                        txtPassword.getPassword()
                );

        String confirmPassword =
                new String(
                        txtConfirmPassword.getPassword()
                );

        String role =
                cmbRole.getSelectedItem()
                        .toString();

        // Validate username
        if (username.isEmpty()) {

            throw new IllegalArgumentException(
                    "Please enter a username."
            );
        }

        // Validate full name
        if (fullName.isEmpty()) {

            throw new IllegalArgumentException(
                    "Please enter the full name."
            );
        }

        // Check username conflict
        User existingUser =
                userService.findByUsername(username);

        if (existingUser != null
                && existingUser.getUserId()
                != userId) {

            throw new IllegalArgumentException(
                    "Username already exists."
            );
        }

        // Create User object
        User user = new User();

        user.setUserId(userId);

        user.setUsername(username);

        user.setFullName(fullName);

        user.setRole(role);

        /*
         * If password fields are empty:
         * keep the existing password.
         *
         * If a new password is entered:
         * hash it before saving.
         */
        boolean changePassword =
                !password.isEmpty();

        if (changePassword) {

            if (!password.equals(
                    confirmPassword)) {

                throw new IllegalArgumentException(
                        "Passwords do not match."
                );
            }

            // IMPORTANT:
            // Hash new password
            user.setPassword(
                    PasswordUtil.hashPassword(
                            password
                    )
            );
        }

        // Update user
        userService.update(
                user,
                changePassword
        );

        // Refresh table
        loadUsers();

        // Keep selected user
        selectUserRow(userId);

        // Clear password fields
        txtPassword.setText("");
        txtConfirmPassword.setText("");

        JOptionPane.showMessageDialog(
                this,
                "User updated successfully."
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "User Update Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         goBackToDashboard();
         this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserForm().setVisible(true));
    }
    
    private void selectUserRow(int userId) {

    DefaultTableModel model =
            (DefaultTableModel)
            tblUsers.getModel();

    for (int i = 0;
            i < model.getRowCount();
            i++) {

        int tableUserId =
                Integer.parseInt(
                        model.getValueAt(i, 0)
                        .toString()
                );

        if (tableUserId == userId) {

            tblUsers.setRowSelectionInterval(
                    i,
                    i
            );

            break;
        }
    }
}
    
    private void clearUserForm() {

    txtUserId.setText("");

    txtUsername.setText("");

    txtFullName.setText("");

    txtPassword.setText("");

    txtConfirmPassword.setText("");

    txtSearchUsername.setText("");

    if (cmbRole.getItemCount() > 0) {

        cmbRole.setSelectedItem(
                "RECEPTIONIST"
        );
    }

    tblUsers.clearSelection();
}
    
    private void goBackToDashboard() {

    DashboardForm dashboard =
            new DashboardForm(currentUser);

    dashboard.setVisible(true);

    this.dispose();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClearUser;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnSaveUser;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblUsers;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSearchUsername;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
